name: C/C++ CI

on:
  push:
    branches: [ cpp14, add-* ]
  pull_request:
    branches: [ cpp14 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     # install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
    - name: git_actions
      run: git submodule update --init --recursive
    - name: cmake
      run: |
        sudo apt update
        sudo apt install mm-common g++-9
        export CXX=g++-9
        cmake .
    - name: make
      run: |
       export CXX=g++-9
       make
    - name: run_tests
      run: |
        pwd
        ctest --output-on-failure
